work_path=$(dirname $0)
cd ${work_path}
rm -rf include
mkdir include
mkdir include/xhnSTL
cp ../xhnSTL/xlibc/array.h                                       include/xhnSTL/array.h
cp ../xhnSTL/xlibc/comparison_algorithm.h           include/xhnSTL/comparison_algorithm.h
cp ../xhnSTL/xlibc/container.h                                include/xhnSTL/container.h
cp ../xhnSTL/xlibc/eassert.h                                    include/xhnSTL/eassert.h
cp ../xhnSTL/xlibc/elog.h                                         include/xhnSTL/elog.h
cp ../xhnSTL/xlibc/emem.h                                      include/xhnSTL/emem.h
cp ../xhnSTL/xlibc/emem_allocator.h                       include/xhnSTL/emem_allocator.h
cp ../xhnSTL/xlibc/esignal.h                                     include/xhnSTL/esignal.h
cp ../xhnSTL/xlibc/estring.h                                     include/xhnSTL/estring.h
cp ../xhnSTL/xlibc/exception.h                                include/xhnSTL/exception.h
cp ../xhnSTL/xlibc/hash.h                                        include/xhnSTL/hash.h
cp ../xhnSTL/xlibc/list.h                                           include/xhnSTL/list.h
cp ../xhnSTL/xlibc/list_base.h                                  include/xhnSTL/list_base.h
#cp ../xhnSTL/xlibc/mem.h                                     include/xhnSTL/mem.h
cp ../xhnSTL/xlibc/prime.h                                      include/xhnSTL/prime.h
cp ../xhnSTL/xlibc/rwbuffer.h                                 include/xhnSTL/rwbuffer.h
cp ../xhnSTL/xlibc/sha256.h                                   include/xhnSTL/sha256.h
cp ../xhnSTL/xlibc/spin_lock.h                                include/xhnSTL/spin_lock.h
cp ../xhnSTL/xlibc/stack.h                                      include/xhnSTL/stack.h
cp ../xhnSTL/xlibc/static_string.h                           include/xhnSTL/static_string.h
cp ../xhnSTL/xlibc/tree.h                                        include/xhnSTL/tree.h
cp ../xhnSTL/xlibc/utility.h                                     include/xhnSTL/utility.h
cp ../xhnSTL/xlibc/cpu.h                                       include/xhnSTL/cpu.h

cp ../xhnSTL/xstl/map.hpp                                    include/xhnSTL/map.hpp
cp ../xhnSTL/xstl/rtti.hpp                                      include/xhnSTL/rtti.hpp
cp ../xhnSTL/xstl/timer.h                                      include/xhnSTL/timer.h
cp ../xhnSTL/xstl/xhn_atomic_bool.hpp               include/xhnSTL/xhn_atomic_bool.hpp
cp ../xhnSTL/xstl/xhn_atomic_operation.hpp      include/xhnSTL/xhn_atomic_operation.hpp
cp ../xhnSTL/xstl/xhn_atomic_ptr.hpp                 include/xhnSTL/xhn_atomic_ptr.hpp
cp ../xhnSTL/xstl/xhn_cache.hpp                         include/xhnSTL/xhn_cache.hpp
cp ../xhnSTL/xstl/xhn_concurrent.hpp                include/xhnSTL/xhn_concurrent.hpp
cp ../xhnSTL/xstl/xhn_dictionary.hpp                  include/xhnSTL/xhn_dictionary.hpp
cp ../xhnSTL/xstl/xhn_group.hpp                        include/xhnSTL/xhn_group.hpp
cp ../xhnSTL/xstl/xhn_hash_map.hpp                 include/xhnSTL/xhn_hash_map.hpp
cp ../xhnSTL/xstl/xhn_hash_set.hpp                    include/xhnSTL/xhn_hash_set.hpp
cp ../xhnSTL/xstl/xhn_btree.hpp                          include/xhnSTL/xhn_btree.hpp
cp ../xhnSTL/xstl/xhn_cloned_ptr.hpp                 include/xhnSTL/xhn_cloned_ptr.hpp
cp ../xhnSTL/xstl/xhn_config.hpp                         include/xhnSTL/xhn_config.hpp
cp ../xhnSTL/xstl/xhn_crypto.hpp                         include/xhnSTL/xhn_crypto.hpp
cp ../xhnSTL/xstl/xhn_duplicate_finder.h             include/xhnSTL/xhn_duplicate_finder.h
cp ../xhnSTL/xstl/xhn_exception.hpp                   include/xhnSTL/xhn_exception.hpp
cp ../xhnSTL/xstl/xhn_file_stream.hpp                 include/xhnSTL/xhn_file_stream.hpp
cp ../xhnSTL/xstl/xhn_fixed_queue.hpp              include/xhnSTL/xhn_fixed_queue.hpp
cp ../xhnSTL/xstl/xhn_math.hpp                          include/xhnSTL/xhn_math.hpp
cp ../xhnSTL/xstl/xhn_open_hash_set.hpp           include/xhnSTL/xhn_open_hash_set.hpp
cp ../xhnSTL/xstl/xhn_parallel.hpp                       include/xhnSTL/xhn_parallel.hpp
cp ../xhnSTL/xstl/xhn_state_machine.hpp           include/xhnSTL/xhn_state_machine.hpp
cp ../xhnSTL/xstl/xhn_triple_buffer.hpp              include/xhnSTL/xhn_triple_buffer.hpp
cp ../xhnSTL/xstl/xhn_tuple.hpp                          include/xhnSTL/xhn_tuple.hpp
cp ../xhnSTL/xstl/xhn_functor.hpp                       include/xhnSTL/xhn_functor.hpp
cp ../xhnSTL/xstl/xhn_garbage_collector.hpp      include/xhnSTL/xhn_garbage_collector.hpp
cp ../xhnSTL/xstl/xhn_gc_array.h                          include/xhnSTL/xhn_gc_array.h
cp ../xhnSTL/xstl/xhn_gc_container_base.h         include/xhnSTL/xhn_gc_container_base.h
cp ../xhnSTL/xstl/xhn_gc_string.h                        include/xhnSTL/xhn_gc_string.h
cp ../xhnSTL/xstl/xhn_gc_values.h                        include/xhnSTL/xhn_gc_values.h
cp ../xhnSTL/xstl/xhn_hash_set.hpp                     include/xhnSTL/xhn_hash_set.hpp
cp ../xhnSTL/xstl/xhn_iterator.hpp                      include/xhnSTL/xhn_iterator.hpp
cp ../xhnSTL/xstl/xhn_lambda.hpp                      include/xhnSTL/xhn_lambda.hpp
cp ../xhnSTL/xstl/xhn_list.hpp                             include/xhnSTL/xhn_list.hpp
cp ../xhnSTL/xstl/xhn_list2.h                                include/xhnSTL/xhn_list2.h
cp ../xhnSTL/xstl/xhn_list_template.hpp              include/xhnSTL/xhn_list_template.hpp
cp ../xhnSTL/xstl/xhn_lock.hpp                            include/xhnSTL/xhn_lock.hpp
cp ../xhnSTL/xstl/xhn_map.hpp                           include/xhnSTL/xhn_map.hpp
cp ../xhnSTL/xstl/xhn_memory.hpp                                         include/xhnSTL/xhn_memory.hpp
#cp ../xhnSTL/xstl/xhn_open_addressing_hash_table.hpp      include/xhnSTL/xhn_open_addressing_hash_table.hpp
cp ../xhnSTL/xstl/xhn_operation.hpp                                      include/xhnSTL/xhn_operation.hpp
cp ../xhnSTL/xstl/xhn_operation_manager.hpp                      include/xhnSTL/xhn_operation_manager.hpp
cp ../xhnSTL/xstl/xhn_pair.hpp                                                include/xhnSTL/xhn_pair.hpp
cp ../xhnSTL/xstl/xhn_rbtree.hpp                                            include/xhnSTL/xhn_rbtree.hpp
cp ../xhnSTL/xstl/xhn_recursive.hpp                                       include/xhnSTL/xhn_recursive.hpp
cp ../xhnSTL/xstl/xhn_routine_pool.hpp                                include/xhnSTL/xhn_routine_pool.hpp
cp ../xhnSTL/xstl/xhn_set.hpp                                                include/xhnSTL/xhn_set.hpp
cp ../xhnSTL/xstl/xhn_singly_linked_list.hpp                           include/xhnSTL/xhn_singly_linked_list.hpp
cp ../xhnSTL/xstl/xhn_smart_ptr.hpp                                      include/xhnSTL/xhn_smart_ptr.hpp
cp ../xhnSTL/xstl/xhn_state_machine.hpp                              include/xhnSTL/xhn_state_machine.hpp
cp ../xhnSTL/xstl/xhn_static_string.hpp                                 include/xhnSTL/xhn_static_string.hpp
cp ../xhnSTL/xstl/xhn_string.hpp                                           include/xhnSTL/xhn_string.hpp
cp ../xhnSTL/xstl/xhn_string_base.hpp                                  include/xhnSTL/xhn_string_base.hpp
cp ../xhnSTL/xstl/xhn_thread.hpp                                          include/xhnSTL/xhn_thread.hpp
cp ../xhnSTL/xstl/xhn_thread_map.hpp                                 include/xhnSTL/xhn_thread_map.hpp
cp ../xhnSTL/xstl/xhn_thread_pool.hpp                                 include/xhnSTL/xhn_thread_pool.hpp
cp ../xhnSTL/xstl/xhn_tuple.hpp                                            include/xhnSTL/xhn_tuple.hpp
cp ../xhnSTL/xstl/xhn_unique_identifier.hpp                        include/xhnSTL/xhn_unique_identifier.hpp
cp ../xhnSTL/xstl/xhn_utility.hpp                                          include/xhnSTL/xhn_utility.hpp
cp ../xhnSTL/xstl/xhn_vector.hpp                                         include/xhnSTL/xhn_vector.hpp
cp ../xhnSTL/xstl/xhn_void_vector.hpp                                include/xhnSTL/xhn_void_vector.hpp
cp ../xhnSTL/xstl/xhn_neural_network.hpp                         include/xhnSTL/xhn_neural_network.hpp
cp ../xhnSTL/xstl/xhn_logger.hpp                                        include/xhnSTL/xhn_logger.hpp
cp ../xhnSTL/xstl/xhn_stacktrace.hpp                                  include/xhnSTL/xhn_stacktrace.hpp

cp ./xhnSTL/common.h                                                                       include/xhnSTL/common.h
cp ./xhnSTL/etypes.h                                                                          include/xhnSTL/etypes.h

